lib/sberbank_web/router.ex
defmodule SberbankWeb.Router do
  use SberbankWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_root_layout, {SberbankWeb.LayoutView, :root}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SberbankWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/employers", EmployerController do
      live "/tickets", OperatorTicketsLive
    end

    resources "/competencies", CompetenceController

    resources "/customers", CustomerController do
      resources "/tickets", CustomerTicketsController, only: [:index, :create, :update, :delete]
    end

    resources "/tickets", TicketController
  end

  # Other scopes may use custom stacks.
  # scope "/api", SberbankWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: SberbankWeb.Telemetry
    end
  end
end

lib/sberbank_web/views/layout_view.ex
defmodule SberbankWeb.LayoutView do
  use SberbankWeb, :view

  def get_flash_if_exist(conn, type, class_name) do
    message = get_flash(conn, type)

    if message do
      content_tag(:p, message, class: "alert #{class_name}", role: "alert")
    end
  end
end

lib/sberbank_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>
  <body>
    <%= @inner_content %>
  </body>
</html>

lib/sberbank_web/templates/layout/root.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Sberbank" %>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header class="container">
      <section>
        <nav role="navigation"  class="navbar navbar-expand justify-content-end bg-light">
          <ul class="navbar-nav">
            <li class="nav-item"><%= link "Employers", to: Routes.employer_path(@conn, :index), class: "nav-link" %></li>
            <li class="nav-item"><%= link "Competencies", to: Routes.competence_path(@conn, :index), class: "nav-link" %></li>
            <li class="nav-item"><%= link "Customers", to: Routes.customer_path(@conn, :index), class: "nav-link" %></li>
            <li class="nav-item"><%= link "Tickets", to: Routes.ticket_path(@conn, :index), class: "nav-link" %></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
            <li class="nav-item"><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home), class: "nav-link" %></li>
            <% end %>
          </ul>
        </nav>
      </section>
    </header>

    <main role="main" class="container">
      <%= get_flash_if_exist(@conn, :info, "alert-info") %>
      <%= get_flash_if_exist(@conn, :error, "alert-danger") %>
      <%= @inner_content %>
    </main>
  </body>
</html>